#!/bin/bash

source $(dirname $0)/panel/config

bspc config border_width    3
bspc config window_gap      "$WINDOW_GAP"
bspc config top_padding     "$PANEL_HEIGHT"

MONS=( $(bspc query -M) )
NBWS=$((10 / ${#MONS[*]}))

for i in ${!MONS[*]}
do
    bspc monitor "${MONS[$i]}" \
        -n "$((i+1))" \
        -d $(printf '%0.s- ' $(seq 1 ${NBWS}))
done

bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config paddingless_monocle         false
bspc config click_to_focus              false
bspc config focus_follows_pointer       true
bspc config pointer_follows_focus       false
bspc config pointer_follows_monitor     true
bspc config ignore_ewmh_focus           false
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true

# colors
bspc config normal_border_color 	        "#373b41"
bspc config active_border_color 	        "#707070"
bspc config focused_border_color 	        "#15814c"
bspc config presel_feedback_color 	        "#707880"


# Rules
bspc rule -a Tilda state=floating focus=on locked=on manage=on border=off
bspc rule -a mpv state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Gimp state=floating
bspc rule -a Virt-viewer state=floating
bspc rule -a Sxiv state=floating
bspc rule -a Qemu-system-x86_64 state=floating

