#!/bin/bash

source $(dirname $0)/panel/config

bspc config border_width        5
bspc config window_gap          "$WINDOW_GAP"

MONS=( $(bspc query -M) )
NBWS=$((10 / ${#MONS[*]}))

for i in ${!MONS[*]}
do
    bspc monitor "${MONS[$i]}" \
        -n "$((i+1))" \
        -d $(printf '%0.s- ' $(seq 1 ${NBWS}))
done

# Visual options
bspc config split_ratio         	        0.50
bspc config borderless_monocle  	        true
bspc config gapless_monocle     	        true
bspc config focus_follows_pointer 	        true
bspc config auto_alternate 		            true
bspc config auto_cancel 		            true
bspc config normal_border_color 	        "#373b41"
bspc config active_border_color 	        "#707070"
bspc config focused_border_color 	        "#c9c1ba"
bspc config presel_feedback_color 	        "#707880"
bspc config urgent_border_color 	        "#9f7155"
bspc config focused_locked_border_color     "#9a875f"
bspc config normal_frame_opacity 	        0.0
bspc config focused_frame_opacity 	        0.1
bspc config remove_disabled_monitors        true
bspc config remove_unplugged_monitors       true

# Rules
bspc rule -a Gmrun state=floating
bspc rule -a Thunar state=floating
bspc rule -a Tilda state=floating focus=on locked=on manage=on border=off
bspc rule -a Mpv state=floating
bspc rule -a Conky ticky=on manage=off lower=on
bspc rule -a Pavucontrol state=floating
bspc rule -a Virt-viewer state=floating
bspc rule -a Sxiv state=floating
bspc rule -a Qemu-system-x86_64 state=floating

killall panel
~/.config/bspwm/panel/panel &
